[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd packages/backend && npm install"
watchPatterns = ["packages/backend/**"]

[deploy]
startCommand = "sh -c 'cd packages/backend && npm run start:prod'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
workingDirectory = "packages/backend"

[[deploy.healthcheck]]
httpPath = "/health"
port = 4100

[[deploy.healthcheck]]
httpPath = "/health"
port = 8080
