[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd packages/backend && npm install && cd ../ml-service && pip install -r requirements.txt"

[deploy]
startCommand = "cd packages/backend && npm run start:prod && npm run seed"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
httpPath = "/health"
port = 4100

[[deploy.healthcheck]]
httpPath = "/health"
port = 8080
