[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/backend/Dockerfile"
watchPatterns = ["packages/backend/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
httpPath = "/health"
port = 4100

[[deploy.healthcheck]]
httpPath = "/health"
port = 8080
