[build]
builder = "NIXPACKS"
buildCommand = "npm run install:all"

[deploy]
startCommand = "npm run start:all"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
httpPath = "/health"
port = 4100

[[deploy.healthcheck]]
httpPath = "/health"
port = 5000
